### ISSUE TITLE
Uncountables can be pluralized

### ISSUE THREAD

**Issue by dlee** [FinNLP/en-inflectors#2]
There are many words in your uncountables list that are commonly found pluralized. A sampling of such words include:
* art
* currency
* damage
* energy
* justice
* labor
* metal
* money
* power
* quantity
* room
* sorrow
* space
* sport
* strength
* trade

There should be a way to pluralize these words.

**Comment by davesag** [comment]
All of those words can in fact be pluralised.

- "She works in the arts"
- "They support multiple currencies"
- "He was awarded damages"
- "The exchange handles pricing for a range of energies"
- "The Justices conferred"
- "She was rewarded for her labours"
- "The alloy is a mix of three rare metals"
- "It allows various monies"
- "She used her powers for good instead of evil"
- "There are three quantities involved here"
- "The carpet is stained in two rooms"
- "When he opened Pandora's Box he unleashed all the sorrows of the world"
- "There are six spaces in this sentence."
- "She excels at several sports"
- "Javascript has many strengths, and few weaknesses"
- "He made four separate trades before the police arrested him"

**Comment by alexcorvi** [comment]
Fixed! thanks.
